const assert = require("assert");
const { buildAdaptiveFuelingProposal, approveAdaptiveFuelingProposal } = require("../assets/js/adaptive-fueling.js");
const targets = { calories: 2000, protein: 150, carbs: 220, fat: 70 };
const days = Array.from({ length: 4 }, (_, index) => ({ date: `2026-07-${20 + index}`, calories: 2000, protein: 150 }));
assert.strictEqual(buildAdaptiveFuelingProposal({ targets: {} }).status, "NEEDS TARGETS");
assert.strictEqual(buildAdaptiveFuelingProposal({ targets, nutritionDays: days.slice(0, 2) }).status, "LEARNING");
assert.strictEqual(buildAdaptiveFuelingProposal({ targets, nutritionDays: days.map((day) => ({ ...day, calories: 1400 })) }).status, "HOLD");
const maintain = buildAdaptiveFuelingProposal({ targets, nutritionDays: days, goal: "MAINTAIN", readiness: "GREEN" });
assert.strictEqual(maintain.status, "READY FOR APPROVAL");
assert.strictEqual(maintain.trainingTargets.carbs, 240);
assert.strictEqual(maintain.trainingTargets.fat, 61);
const performance = buildAdaptiveFuelingProposal({ targets, nutritionDays: days, goal: "PERFORMANCE", readiness: "GREEN" });
assert.ok(performance.trainingTargets.calories > targets.calories && performance.trainingTargets.calories <= targets.calories + 150);
assert.strictEqual(performance.trainingTargets.protein, targets.protein);
const reduced = buildAdaptiveFuelingProposal({ targets, nutritionDays: days, goal: "PERFORMANCE", readiness: "YELLOW" });
assert.deepStrictEqual(reduced.trainingTargets, targets);
const fatLoss = buildAdaptiveFuelingProposal({ targets, nutritionDays: days, goal: "FAT_LOSS", readiness: "GREEN" });
assert.strictEqual(fatLoss.trainingTargets.calories, targets.calories);
assert.match(fatLoss.strategy, /automatic calorie cuts/i);
assert.throws(() => approveAdaptiveFuelingProposal({ status: "LEARNING" }));
assert.strictEqual(approveAdaptiveFuelingProposal(maintain, "2026-07-27T12:00:00Z").status, "APPROVED");
console.log("adaptive fueling tests passed");
